import type { Room } from "./room.model.js";

export interface DB {
  rooms: Room[];
}

export const db: DB = {
  rooms: [
    {
      _id: "1",
      listing_url: "https://www.airbnb.com/rooms/10006546",
      name: "Ribeira Charming Duplex",
      summary:
        "Fantastic duplex apartment with three bedrooms in historic center.",
      space: "Privileged views of the Douro River and Ribeira square.",
      description:
        "Fantastic duplex apartment with three bedrooms, located in the historic center of Porto.",
      neighborhood_overview: "Close to river, restaurants, and shops.",
      notes: "Narrow streets and staircases nearby.",
      transit: "Metro station 5min walk, bus stop 2min walk.",
      access: "Full apartment access for guests.",
      interaction: "Hosts are available 24/7 via phone.",
      house_rules: "No smoking, no pets, quiet hours after 10pm.",
      property_type: "House",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "2",
      maximum_nights: "30",
      cancellation_policy: "moderate",
      last_scraped: "2019-02-16T05:00:00.000Z",
      calendar_last_scraped: "2019-02-16T05:00:00.000Z",
      first_review: "2016-01-03T05:00:00.000Z",
      last_review: "2019-01-20T05:00:00.000Z",
      accommodates: 8,
      bedrooms: 3,
      beds: 5,
      number_of_reviews: 51,
      bathrooms: 1,
      amenities: [
        "WiFi",
        "Heating",
        "Kitchen",
        "Washer",
        "Dryer",
        "TV",
        "Smoke alarm",
      ],
      price: 80,
      security_deposit: 200,
      cleaning_fee: 35,
      extra_people: 15,
      guests_included: 6,
      images: {
        thumbnail_url: "https://example.com/thumb1.jpg",
        medium_url: "https://example.com/medium1.jpg",
        picture_url: "https://example.com/pic1.jpg",
        xl_picture_url: "https://example.com/xlpic1.jpg",
      },
      host: {
        host_id: "12345",
        host_url: "https://www.airbnb.com/users/show/12345",
        host_name: "Alice",
        host_location: "Porto",
        host_about: "Experienced host, love meeting new people.",
        host_response_time: "within an hour",
        host_thumbnail_url: "https://example.com/hostthumb1.jpg",
        host_picture_url: "https://example.com/hostpic1.jpg",
        host_neighbourhood: "Downtown Porto",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 3,
      },
      address: {
        street: "Rua da Ribeira 10",
        suburb: "Ribeira",
        government_area: "Porto",
        market: "Porto Center",
        country: "Portugal",
        country_code: "PT",
        location: {
          type: "Point",
          coordinates: [-8.611, 41.14],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 20,
        availability_60: 45,
        availability_90: 70,
        availability_365: 300,
      },
      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 10,
        review_scores_checkin: 9,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 8,
        review_scores_rating: 9,
      },
      reviews: [
        {
          _id: "r1",
          date: "2019-01-10",
          reviewer_id: "u100",
          reviewer_name: "John Doe",
          comments: "Great stay, highly recommend!",
        },
        {
          _id: "r2",
          date: "2019-01-15",
          reviewer_id: "u101",
          reviewer_name: "Jane Smith",
          comments: "Lovely place and very clean.",
        },
      ],
    },
    {
      _id: "2",
      listing_url: "https://www.airbnb.com/rooms/10006547",
      name: "Cozy Studio Downtown",
      summary: "Perfect for couples, near city attractions.",
      space: "Compact studio with modern amenities.",
      description: "Cozy studio apartment ideal for short stays in downtown.",
      neighborhood_overview: "Close to museums and restaurants.",
      notes: "Quiet neighborhood.",
      transit: "Close to subway station.",
      access: "Self check-in via lockbox.",
      interaction: "Available by message.",
      house_rules: "No pets, no parties.",
      property_type: "Apartment",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "1",
      maximum_nights: "15",
      cancellation_policy: "flexible",
      last_scraped: "2019-03-10T05:00:00.000Z",
      calendar_last_scraped: "2019-03-10T05:00:00.000Z",
      first_review: "2017-05-01T05:00:00.000Z",
      last_review: "2019-02-20T05:00:00.000Z",
      accommodates: 2,
      bedrooms: 0,
      beds: 1,
      number_of_reviews: 34,
      bathrooms: 1,
      amenities: ["WiFi", "Heating", "Kitchen", "TV"],
      price: 50,
      security_deposit: 100,
      cleaning_fee: 20,
      extra_people: 10,
      guests_included: 1,
      images: {
        thumbnail_url: "https://example.com/thumb2.jpg",
        medium_url: "https://example.com/medium2.jpg",
        picture_url: "https://example.com/pic2.jpg",
        xl_picture_url: "https://example.com/xlpic2.jpg",
      },
      host: {
        host_id: "12346",
        host_url: "https://www.airbnb.com/users/show/12346",
        host_name: "Bob",
        host_location: "Lisbon",
        host_about: "Love hosting travelers.",
        host_response_time: "within a few hours",
        host_thumbnail_url: "https://example.com/hostthumb2.jpg",
        host_picture_url: "https://example.com/hostpic2.jpg",
        host_neighbourhood: "City Center",
        host_is_superhost: false,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 1,
      },
      address: {
        street: "Rua das Flores 5",
        suburb: "Centro",
        government_area: "Lisbon",
        market: "Lisbon Center",
        country: "Portugal",
        country_code: "PT",
        location: {
          type: "Point",
          coordinates: [-9.142, 38.722],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 10,
        availability_60: 20,
        availability_90: 50,
        availability_365: 200,
      },
      review_scores: {
        review_scores_accuracy: 8,
        review_scores_cleanliness: 9,
        review_scores_checkin: 8,
        review_scores_communication: 9,
        review_scores_location: 9,
        review_scores_value: 8,
        review_scores_rating: 8,
      },
      reviews: [
        {
          _id: "r3",
          date: "2019-02-10",
          reviewer_id: "u102",
          reviewer_name: "Alice Johnson",
          comments: "Very cozy and well located.",
        },
      ],
    },
    {
      _id: "3",
      listing_url: "https://www.airbnb.com/rooms/10006548",
      name: "Modern Loft with Views",
      summary: "Spacious loft with river views.",
      space: "Open space loft with large windows.",
      description: "Modern loft located near the river with stunning views.",
      neighborhood_overview: "Trendy area with cafes and galleries.",
      notes: "Parking available nearby.",
      transit: "Bus stop 3 minutes away.",
      access: "Keypad entry system.",
      interaction: "Hosts live nearby.",
      house_rules: "No smoking, no pets.",
      property_type: "Loft",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "3",
      maximum_nights: "30",
      cancellation_policy: "strict",
      last_scraped: "2019-01-20T05:00:00.000Z",
      calendar_last_scraped: "2019-01-20T05:00:00.000Z",
      first_review: "2017-07-15T05:00:00.000Z",
      last_review: "2019-01-10T05:00:00.000Z",
      accommodates: 4,
      bedrooms: 1,
      beds: 2,
      number_of_reviews: 20,
      bathrooms: 1,
      amenities: ["WiFi", "Heating", "Kitchen", "TV", "Air conditioning"],
      price: 120,
      security_deposit: 300,
      cleaning_fee: 40,
      extra_people: 20,
      guests_included: 2,
      images: {
        thumbnail_url: "https://example.com/thumb3.jpg",
        medium_url: "https://example.com/medium3.jpg",
        picture_url: "https://example.com/pic3.jpg",
        xl_picture_url: "https://example.com/xlpic3.jpg",
      },
      host: {
        host_id: "12347",
        host_url: "https://www.airbnb.com/users/show/12347",
        host_name: "Charlie",
        host_location: "Porto",
        host_about: "Passionate about hosting.",
        host_response_time: "within a day",
        host_thumbnail_url: "https://example.com/hostthumb3.jpg",
        host_picture_url: "https://example.com/hostpic3.jpg",
        host_neighbourhood: "Ribeira",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 2,
      },
      address: {
        street: "Rua Nova 15",
        suburb: "Ribeira",
        government_area: "Porto",
        market: "Porto Center",
        country: "Portugal",
        country_code: "PT",
        location: {
          type: "Point",
          coordinates: [-8.61, 41.141],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 25,
        availability_60: 50,
        availability_90: 75,
        availability_365: 320,
      },
      review_scores: {
        review_scores_accuracy: 10,
        review_scores_cleanliness: 10,
        review_scores_checkin: 9,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 9,
        review_scores_rating: 10,
      },
      reviews: [
        {
          _id: "r4",
          date: "2019-01-05",
          reviewer_id: "u103",
          reviewer_name: "Eve Martin",
          comments: "Wonderful loft with great views.",
        },
      ],
    },
    {
      _id: "4",
      listing_url: "https://www.airbnb.com/rooms/10006549",
      name: "Seaside Cottage",
      summary: "Cozy cottage by the sea.",
      space: "Cottage with garden and terrace.",
      description: "Beautiful seaside cottage perfect for summer holidays.",
      neighborhood_overview: "Quiet village close to the beach.",
      notes: "Ideal for families.",
      transit: "Limited public transport.",
      access: "Private parking included.",
      interaction: "Hosts check in person.",
      house_rules: "No loud music after 9pm.",
      property_type: "Cottage",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "4",
      maximum_nights: "28",
      cancellation_policy: "moderate",
      last_scraped: "2019-04-01T05:00:00.000Z",
      calendar_last_scraped: "2019-04-01T05:00:00.000Z",
      first_review: "2016-06-01T05:00:00.000Z",
      last_review: "2019-03-20T05:00:00.000Z",
      accommodates: 6,
      bedrooms: 2,
      beds: 3,
      number_of_reviews: 40,
      bathrooms: 2,
      amenities: ["WiFi", "Kitchen", "Heating", "Fireplace"],
      price: 95,
      security_deposit: 250,
      cleaning_fee: 30,
      extra_people: 10,
      guests_included: 4,
      images: {
        thumbnail_url: "https://example.com/thumb4.jpg",
        medium_url: "https://example.com/medium4.jpg",
        picture_url: "https://example.com/pic4.jpg",
        xl_picture_url: "https://example.com/xlpic4.jpg",
      },
      host: {
        host_id: "12348",
        host_url: "https://www.airbnb.com/users/show/12348",
        host_name: "Diana",
        host_location: "Algarve",
        host_about: "Friendly host, love nature.",
        host_response_time: "within a few hours",
        host_thumbnail_url: "https://example.com/hostthumb4.jpg",
        host_picture_url: "https://example.com/hostpic4.jpg",
        host_neighbourhood: "Beachside",
        host_is_superhost: false,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 4,
      },
      address: {
        street: "Rua da Praia 20",
        suburb: "Praia",
        government_area: "Algarve",
        market: "Algarve Region",
        country: "Portugal",
        country_code: "PT",
        location: {
          type: "Point",
          coordinates: [-8.25, 37.02],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 15,
        availability_60: 35,
        availability_90: 60,
        availability_365: 250,
      },
      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 9,
        review_scores_checkin: 9,
        review_scores_communication: 10,
        review_scores_location: 9,
        review_scores_value: 8,
        review_scores_rating: 9,
      },
      reviews: [
        {
          _id: "r5",
          date: "2019-03-15",
          reviewer_id: "u104",
          reviewer_name: "Frank Lee",
          comments: "Perfect place for a relaxing vacation.",
        },
      ],
    },
    {
      _id: "5",
      listing_url: "https://www.airbnb.com/rooms/10006550",
      name: "Mountain Cabin Retreat",
      summary: "Rustic cabin with mountain views.",
      space: "Cabin surrounded by nature.",
      description: "Cozy mountain cabin perfect for hiking lovers.",
      neighborhood_overview: "Secluded area with trails.",
      notes: "Limited cell coverage.",
      transit: "No public transport nearby.",
      access: "Guests have full access.",
      interaction: "Hosts live nearby and available by phone.",
      house_rules: "No smoking, no loud parties.",
      property_type: "Cabin",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "3",
      maximum_nights: "21",
      cancellation_policy: "strict",
      last_scraped: "2019-01-01T05:00:00.000Z",
      calendar_last_scraped: "2019-01-01T05:00:00.000Z",
      first_review: "2017-01-15T05:00:00.000Z",
      last_review: "2018-12-20T05:00:00.000Z",
      accommodates: 5,
      bedrooms: 2,
      beds: 3,
      number_of_reviews: 15,
      bathrooms: 1,
      amenities: ["WiFi", "Heating", "Fireplace", "Kitchen"],
      price: 75,
      security_deposit: 150,
      cleaning_fee: 25,
      extra_people: 10,
      guests_included: 3,
      images: {
        thumbnail_url: "https://example.com/thumb5.jpg",
        medium_url: "https://example.com/medium5.jpg",
        picture_url: "https://example.com/pic5.jpg",
        xl_picture_url: "https://example.com/xlpic5.jpg",
      },
      host: {
        host_id: "12349",
        host_url: "https://www.airbnb.com/users/show/12349",
        host_name: "Ethan",
        host_location: "Sierra Nevada",
        host_about: "Nature lover and experienced host.",
        host_response_time: "within a day",
        host_thumbnail_url: "https://example.com/hostthumb5.jpg",
        host_picture_url: "https://example.com/hostpic5.jpg",
        host_neighbourhood: "Mountain area",
        host_is_superhost: false,
        host_has_profile_pic: true,
        host_identity_verified: false,
        host_listings_count: 1,
      },
      address: {
        street: "Calle Montaña 1",
        suburb: "Highlands",
        government_area: "Sierra Nevada",
        market: "Mountain Region",
        country: "Spain",
        country_code: "ES",
        location: {
          type: "Point",
          coordinates: [-3.4, 37.0],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 5,
        availability_60: 15,
        availability_90: 30,
        availability_365: 100,
      },
      review_scores: {
        review_scores_accuracy: 8,
        review_scores_cleanliness: 9,
        review_scores_checkin: 8,
        review_scores_communication: 9,
        review_scores_location: 7,
        review_scores_value: 8,
        review_scores_rating: 8,
      },
      reviews: [
        {
          _id: "r6",
          date: "2018-12-15",
          reviewer_id: "u105",
          reviewer_name: "Grace Hopper",
          comments: "Peaceful retreat with beautiful nature.",
        },
      ],
    },
    {
      _id: "room001",
      listing_url: "https://example.com/room001",
      name: "Charming Loft in Central Berlin",
      summary: "A cozy loft perfect for solo travelers or couples.",
      space: "Open-plan space with natural light and minimalist decor.",
      description:
        "This charming loft is located in the heart of Berlin with easy access to public transport and major attractions.",
      neighborhood_overview:
        "Lively and artistic district with cafes, galleries, and boutiques.",
      notes: "Please respect quiet hours after 10pm.",
      transit: "2-minute walk to U-Bahn, 5-minute walk to S-Bahn.",
      access: "Full apartment access including kitchen and bathroom.",
      interaction: "Host available via phone or Airbnb chat.",
      house_rules: "No smoking. No parties. No pets.",
      property_type: "Apartment",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "2",
      maximum_nights: "30",
      cancellation_policy: "moderate",
      last_scraped: "2025-07-19",
      calendar_last_scraped: "2025-07-19",
      first_review: "2024-07-01",
      last_review: "2025-06-25",
      accommodates: 2,
      bedrooms: 1,
      beds: 1,
      number_of_reviews: 10,
      bathrooms: 1,
      amenities: ["Wifi", "Kitchen", "Heating", "Washer", "Coffee maker"],
      price: 85,
      security_deposit: 100,
      cleaning_fee: 30,
      extra_people: 15,
      guests_included: 1,
      images: {
        thumbnail_url: "https://example.com/thumb1.jpg",
        medium_url: "https://example.com/med1.jpg",
        picture_url: "https://example.com/pic1.jpg",
        xl_picture_url: "https://example.com/xl1.jpg",
      },
      host: {
        host_id: "host001",
        host_url: "https://example.com/host001",
        host_name: "Anna",
        host_location: "Berlin, Germany",
        host_about: "Architect and travel lover hosting cozy places.",
        host_response_time: "within an hour",
        host_thumbnail_url: "https://example.com/host1_thumb.jpg",
        host_picture_url: "https://example.com/host1_pic.jpg",
        host_neighbourhood: "Mitte",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 3,
      },
      address: {
        street: "Kastanienallee 10",
        suburb: "Mitte",
        government_area: "Berlin",
        market: "Berlin",
        country: "Germany",
        country_code: "DE",
        location: {
          type: "Point",
          coordinates: [13.405, 52.52],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 22,
        availability_60: 42,
        availability_90: 58,
        availability_365: 280,
      },
      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 9,
        review_scores_checkin: 10,
        review_scores_communication: 10,
        review_scores_location: 9,
        review_scores_value: 8,
        review_scores_rating: 9,
      },
      reviews: Array.from({ length: 10 }, (_, i) => ({
        _id: `r001-${i + 1}`,
        date: `2025-0${Math.floor(i / 2) + 1}-0${(i % 5) + 1}`,
        reviewer_id: `u001${i}`,
        reviewer_name: `Guest${i + 1}`,
        comments: `Fantastic stay! Everything was clean and well located.`,
      })),
    },
    {
      _id: "room002",
      listing_url: "https://example.com/room002",
      name: "Modern Studio with City Views",
      summary: "Sleek and stylish studio ideal for business travelers.",
      space: "Compact but fully equipped studio with a balcony.",
      description:
        "Enjoy city skyline views from this 10th-floor modern studio. Fully equipped kitchen and fast WiFi.",
      neighborhood_overview:
        "Located in the financial district, close to restaurants and metro lines.",
      notes: "Check-in via lockbox.",
      transit: "1-minute walk to metro line 4.",
      access: "Entire studio and balcony included.",
      interaction: "Self check-in, host available via app.",
      house_rules: "No pets. Quiet hours 10pm-7am.",
      property_type: "Studio",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "3",
      maximum_nights: "14",
      cancellation_policy: "strict",
      last_scraped: "2025-07-19",
      calendar_last_scraped: "2025-07-19",
      first_review: "2024-11-01",
      last_review: "2025-06-30",
      accommodates: 2,
      bedrooms: 1,
      beds: 1,
      number_of_reviews: 10,
      bathrooms: 1,
      amenities: ["Wifi", "Kitchen", "Elevator", "Air conditioning"],
      price: 95,
      security_deposit: 150,
      cleaning_fee: 40,
      extra_people: 20,
      guests_included: 1,
      images: {
        thumbnail_url: "https://example.com/thumb2.jpg",
        medium_url: "https://example.com/med2.jpg",
        picture_url: "https://example.com/pic2.jpg",
        xl_picture_url: "https://example.com/xl2.jpg",
      },
      host: {
        host_id: "host002",
        host_url: "https://example.com/host002",
        host_name: "Luca",
        host_location: "Milan, Italy",
        host_about: "Designer and frequent traveler.",
        host_response_time: "within a few hours",
        host_thumbnail_url: "https://example.com/host2_thumb.jpg",
        host_picture_url: "https://example.com/host2_pic.jpg",
        host_neighbourhood: "Brera",
        host_is_superhost: false,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 2,
      },
      address: {
        street: "Via Dante 45",
        suburb: "Brera",
        government_area: "Milan",
        market: "Milan",
        country: "Italy",
        country_code: "IT",
        location: {
          type: "Point",
          coordinates: [9.19, 45.4654],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 18,
        availability_60: 35,
        availability_90: 50,
        availability_365: 200,
      },
      review_scores: {
        review_scores_accuracy: 10,
        review_scores_cleanliness: 9,
        review_scores_checkin: 9,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 8,
        review_scores_rating: 9,
      },
      reviews: Array.from({ length: 10 }, (_, i) => ({
        _id: `r002-${i + 1}`,
        date: `2025-0${Math.floor(i / 2) + 1}-1${i % 5}`,
        reviewer_id: `u002${i}`,
        reviewer_name: `Traveler${i + 1}`,
        comments: `Great location and views. Would definitely return.`,
      })),
    },
    {
      _id: "room003",
      listing_url: "https://example.com/room003",
      name: "Rustic Cabin in the Woods",
      summary: "Escape the city in this peaceful woodland retreat.",
      space: "Wooden cabin with fireplace and private terrace.",
      description:
        "Unplug and unwind surrounded by nature. Includes outdoor BBQ area and hiking trails nearby.",
      neighborhood_overview: "Quiet, forested area perfect for nature lovers.",
      notes: "Limited cell service. Perfect for digital detox.",
      transit: "Car recommended. 15 min drive from town.",
      access: "Entire cabin and private garden.",
      interaction: "Minimal. Host available by phone.",
      house_rules: "No loud music. Firewood included.",
      property_type: "Cabin",
      room_type: "Entire home/apt",
      bed_type: "Futon",
      minimum_nights: "2",
      maximum_nights: "10",
      cancellation_policy: "flexible",
      last_scraped: "2025-07-19",
      calendar_last_scraped: "2025-07-19",
      first_review: "2024-10-15",
      last_review: "2025-06-10",
      accommodates: 4,
      bedrooms: 2,
      beds: 3,
      number_of_reviews: 10,
      bathrooms: 1,
      amenities: ["Fireplace", "Kitchen", "Free parking", "BBQ grill"],
      price: 70,
      security_deposit: 50,
      cleaning_fee: 25,
      extra_people: 10,
      guests_included: 2,
      images: {
        thumbnail_url: "https://example.com/thumb3.jpg",
        medium_url: "https://example.com/med3.jpg",
        picture_url: "https://example.com/pic3.jpg",
        xl_picture_url: "https://example.com/xl3.jpg",
      },
      host: {
        host_id: "host003",
        host_url: "https://example.com/host003",
        host_name: "Sara",
        host_location: "Slovenia",
        host_about: "Nature enthusiast offering simple retreats.",
        host_response_time: "within a day",
        host_thumbnail_url: "https://example.com/host3_thumb.jpg",
        host_picture_url: "https://example.com/host3_pic.jpg",
        host_neighbourhood: "Triglav National Park",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 5,
      },
      address: {
        street: "Forest Trail 8",
        suburb: "Triglav",
        government_area: "Bled",
        market: "Slovenia",
        country: "Slovenia",
        country_code: "SI",
        location: {
          type: "Point",
          coordinates: [14.0833, 46.3667],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 10,
        availability_60: 22,
        availability_90: 35,
        availability_365: 150,
      },
      review_scores: {
        review_scores_accuracy: 8,
        review_scores_cleanliness: 9,
        review_scores_checkin: 8,
        review_scores_communication: 9,
        review_scores_location: 10,
        review_scores_value: 10,
        review_scores_rating: 9,
      },
      reviews: Array.from({ length: 10 }, (_, i) => ({
        _id: `r003-${i + 1}`,
        date: `2025-0${Math.floor(i / 2) + 2}-0${(i % 6) + 1}`,
        reviewer_id: `u003${i}`,
        reviewer_name: `Explorer${i + 1}`,
        comments: `So peaceful! Loved the nature and cabin atmosphere.`,
      })),
    },
    {
      _id: "room004",
      listing_url: "https://example.com/room004",
      name: "Sunny Apartment by the Beach",
      summary: "Perfect for a summer vacation near the sea.",
      space: "Bright two-bedroom with balcony and sea views.",
      description:
        "Enjoy your coffee watching the waves. Fully equipped for families or couples.",
      neighborhood_overview:
        "Walkable coastal area with restaurants and bike paths.",
      notes: "Beach towels and umbrella included.",
      transit: "Close to bus lines and bike rentals.",
      access: "Entire apartment and garage space.",
      interaction: "Available in person or via phone.",
      house_rules: "No smoking indoors.",
      property_type: "Apartment",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "3",
      maximum_nights: "21",
      cancellation_policy: "moderate",
      last_scraped: "2025-07-19",
      calendar_last_scraped: "2025-07-19",
      first_review: "2024-06-01",
      last_review: "2025-06-20",
      accommodates: 4,
      bedrooms: 2,
      beds: 2,
      number_of_reviews: 10,
      bathrooms: 1,
      amenities: ["Wifi", "Air conditioning", "Kitchen", "Beach essentials"],
      price: 120,
      security_deposit: 100,
      cleaning_fee: 35,
      extra_people: 15,
      guests_included: 2,
      images: {
        thumbnail_url: "https://example.com/thumb4.jpg",
        medium_url: "https://example.com/med4.jpg",
        picture_url: "https://example.com/pic4.jpg",
        xl_picture_url: "https://example.com/xl4.jpg",
      },
      host: {
        host_id: "host004",
        host_url: "https://example.com/host004",
        host_name: "Carlos",
        host_location: "Valencia, Spain",
        host_about: "Hospitality professional with 10+ years hosting.",
        host_response_time: "within an hour",
        host_thumbnail_url: "https://example.com/host4_thumb.jpg",
        host_picture_url: "https://example.com/host4_pic.jpg",
        host_neighbourhood: "Malvarrosa",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 8,
      },
      address: {
        street: "Avenida del Mar 123",
        suburb: "Malvarrosa",
        government_area: "Valencia",
        market: "Valencia",
        country: "Spain",
        country_code: "ES",
        location: {
          type: "Point",
          coordinates: [-0.3281, 39.4702],
          is_location_exact: true,
        },
      },
      availability: {
        availability_30: 25,
        availability_60: 50,
        availability_90: 80,
        availability_365: 300,
      },
      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 10,
        review_scores_checkin: 10,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 9,
        review_scores_rating: 10,
      },
      reviews: Array.from({ length: 10 }, (_, i) => ({
        _id: `r004-${i + 1}`,
        date: `2025-0${(i % 5) + 3}-1${(i % 4) + 1}`,
        reviewer_id: `u004${i}`,
        reviewer_name: `BeachLover${i + 1}`,
        comments: `Amazing spot, very close to the beach and clean.`,
      })),
    },
    {
      _id: "room005",
      listing_url: "https://example.com/listing/room001",
      name: "Modern Flat in Manhattan",
      summary: "Enjoy city life in a bright, modern apartment.",
      space: "Spacious one-bedroom flat with city views.",
      description:
        "Located in the heart of Manhattan, this flat is ideal for business travelers or tourists.",
      neighborhood_overview:
        "Close to Times Square, Central Park, and great dining options.",
      notes: "Please be respectful of neighbors. No loud music after 10 PM.",
      transit: "1-minute walk to subway station. Bus stop around the corner.",
      access: "Guests have access to the entire apartment.",
      interaction: "I’m always available via message or phone.",
      house_rules: "No smoking. No parties.",
      property_type: "Apartment",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "3",
      maximum_nights: "14",
      cancellation_policy: "strict",
      last_scraped: "2025-07-18",
      calendar_last_scraped: "2025-07-18",
      first_review: "2025-02-15",
      last_review: "2025-07-10",
      accommodates: 2,
      bedrooms: 1,
      beds: 1,
      number_of_reviews: 45,
      bathrooms: 1,

      amenities: ["WiFi", "Kitchen", "Heating", "Air conditioning", "Elevator"],

      price: 120,
      security_deposit: 200,
      cleaning_fee: 40,
      extra_people: 25,
      guests_included: 2,

      images: {
        picture_url: "https://example.com/images/nyc.jpg",
      },

      host: {
        host_id: "host001",
        host_url: "https://example.com/host/host001",
        host_name: "Alex",
        host_location: "New York, USA",
        host_about: "Hosting travelers since 2020.",
        host_response_time: "within an hour",
        host_picture_url: "https://example.com/host/alex.jpg",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 2,
      },

      address: {
        street: "5th Avenue",
        suburb: "Midtown",
        government_area: "Manhattan",
        market: "New York",
        country: "United States",
        country_code: "US",
        location: {
          type: "Point",
          coordinates: [-73.9851, 40.758],
          is_location_exact: true,
        },
      },

      availability: {
        availability_30: 18,
        availability_60: 32,
        availability_90: 50,
        availability_365: 260,
      },

      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 9,
        review_scores_checkin: 10,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 8,
        review_scores_rating: 9,
      },

      reviews: [
        {
          date: "2025-07-10",
          reviewer_id: "rev001",
          reviewer_name: "Liam",
          comments: "Great location and very clean!",
        },
      ],
    },
    {
      _id: "room006",
      listing_url: "https://example.com/listing/room002",
      name: "Bright Studio Near Alexanderplatz",
      summary: "Quiet and minimal design in a trendy area.",
      space: "Studio with one double bed and kitchenette.",
      description:
        "Perfect for solo travelers or couples looking to explore Berlin.",
      neighborhood_overview: "Walking distance to cafes, bars, and the U-Bahn.",
      notes: "Please water the plant if staying more than 3 nights 😊",
      transit: "5-minute walk to Alexanderplatz station.",
      access: "Private entrance. Access to garden area.",
      interaction: "I’ll meet you at check-in, then I’m available by phone.",
      house_rules: "No smoking. No shoes indoors.",
      property_type: "Studio",
      room_type: "Entire home/apt",
      bed_type: "Futon",
      minimum_nights: "2",
      maximum_nights: "21",
      cancellation_policy: "flexible",
      last_scraped: "2025-07-18",
      calendar_last_scraped: "2025-07-18",
      first_review: "2025-03-05",
      last_review: "2025-07-15",
      accommodates: 2,
      bedrooms: 1,
      beds: 1,
      number_of_reviews: 18,
      bathrooms: 1,

      amenities: ["WiFi", "Heating", "Kitchenette", "Garden view"],

      price: 65,
      security_deposit: 0,
      cleaning_fee: 15,
      extra_people: 10,
      guests_included: 2,

      images: {
        picture_url: "https://example.com/images/berlin.jpg",
      },

      host: {
        host_id: "host002",
        host_url: "https://example.com/host/host002",
        host_name: "Klara",
        host_location: "Berlin, Germany",
        host_about: "Designer and coffee lover.",
        host_response_time: "within a few hours",
        host_picture_url: "https://example.com/host/klara.jpg",
        host_is_superhost: false,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 1,
      },

      address: {
        street: "Karl-Marx-Allee 10",
        suburb: "Mitte",
        government_area: "Berlin",
        market: "Berlin",
        country: "Germany",
        country_code: "DE",
        location: {
          type: "Point",
          coordinates: [13.405, 52.52],
          is_location_exact: true,
        },
      },

      availability: {
        availability_30: 22,
        availability_60: 40,
        availability_90: 65,
        availability_365: 200,
      },

      review_scores: {
        review_scores_accuracy: 10,
        review_scores_cleanliness: 9,
        review_scores_checkin: 9,
        review_scores_communication: 8,
        review_scores_location: 9,
        review_scores_value: 9,
        review_scores_rating: 9,
      },

      reviews: [
        {
          date: "2025-07-15",
          reviewer_id: "rev003",
          reviewer_name: "Sara",
          comments: "Very peaceful and stylish studio. Great location!",
        },
      ],
    },
    {
      _id: "room007",
      listing_url: "https://example.com/listing/room003",
      name: "Rustic Farmhouse with Vineyard View",
      summary: "Escape to the Tuscan countryside.",
      space: "Large house with 3 bedrooms, terrace, and fireplace.",
      description:
        "Experience authentic Italian living surrounded by olive trees and vineyards.",
      neighborhood_overview:
        "Peaceful area with local markets and traditional trattorias.",
      notes: "WiFi is limited. Great for digital detox!",
      transit: "Car recommended. Free parking available.",
      access: "Full access to house, garden, and private pool.",
      interaction: "We live nearby and are happy to help if needed.",
      house_rules: "No events. Pool hours from 9 AM to 8 PM.",
      property_type: "House",
      room_type: "Entire home/apt",
      bed_type: "Real Bed",
      minimum_nights: "4",
      maximum_nights: "60",
      cancellation_policy: "moderate",
      last_scraped: "2025-07-18",
      calendar_last_scraped: "2025-07-18",
      first_review: "2025-04-01",
      last_review: "2025-06-28",
      accommodates: 6,
      bedrooms: 3,
      beds: 4,
      number_of_reviews: 25,
      bathrooms: 2,

      amenities: ["Fireplace", "Pool", "Garden", "Outdoor dining", "Washer"],

      price: 200,
      security_deposit: 300,
      cleaning_fee: 60,
      extra_people: 0,
      guests_included: 6,

      images: {
        picture_url: "https://example.com/images/tuscany.jpg",
      },

      host: {
        host_id: "host003",
        host_url: "https://example.com/host/host003",
        host_name: "Luca",
        host_location: "Tuscany, Italy",
        host_about: "I run a small family farm. Happy to share local tips!",
        host_response_time: "within a day",
        host_picture_url: "https://example.com/host/luca.jpg",
        host_is_superhost: true,
        host_has_profile_pic: true,
        host_identity_verified: true,
        host_listings_count: 1,
      },

      address: {
        street: "Via della Vigna 45",
        suburb: "Chianti",
        government_area: "Florence",
        market: "Tuscany",
        country: "Italy",
        country_code: "IT",
        location: {
          type: "Point",
          coordinates: [11.2558, 43.7696],
          is_location_exact: true,
        },
      },

      availability: {
        availability_30: 12,
        availability_60: 28,
        availability_90: 40,
        availability_365: 150,
      },

      review_scores: {
        review_scores_accuracy: 9,
        review_scores_cleanliness: 9,
        review_scores_checkin: 10,
        review_scores_communication: 10,
        review_scores_location: 10,
        review_scores_value: 9,
        review_scores_rating: 9,
      },

      reviews: [
        {
          date: "2025-06-28",
          reviewer_id: "rev005",
          reviewer_name: "Thomas",
          comments:
            "Incredible views and warm hospitality. Perfect for a family vacation!",
        },
      ],
    },
  ],
};
